### ISSUE TITLE
Initial issues with this library

### ISSUE THREAD

**Issue by andreasciamanna** [OnTheGoSystems/twig-to-wpml#1]
@zaantar I see two problems with this library even before trying it.

1. It requires PHP 7.1 when WPML is compatible with 5.6+: that may cause issues if the code of this library relies on incompatible features of PHP.
2. It require Twig (obviously).

WPML is moving away from Twig. 

Today, we are using a namespaced customised and PHP 5.6 compatible version of Twig.
In the future, we will completely remove Twig from WPML.

The main reasons for this are:
- Twig isn't really needed. Everything we can do with Twig can be done with plain PHP templates.
- No matter which version of Twig we decide to use, we will always end up having some kind of dependency clash, even if we namespace it. To name a few:
  - outdated version
  - a too updated version
  - a version which conflicts with another version expected by one of our add-ons

I'm not dismissing this proposal, but we will need to study it, assess if we can use it, if we can use it with our customized version of Twig and if it's worth the effort considering our other priorities.

**Comment by zaantar** [comment]
@andreasciamanna, I don't think these issues are actually relevant, probably because we have different ideas about how this tool supposed to be used.

It's a command-line tool that can be applied to a repository, but it isn't really supposed to be its composer dependency. Actually, I was considering turning this into a PHAR at some point. The idea of making it a WP CLI extension is still open but questionable. It's not necessary for the function of this tool and not really needed. So, this way, there is no problem with PHP versions and Twig compatibility when using it.

Regarding the usage of Twig itself, again, I am _not_ suggesting that WPML starts using gettext functions in Twig templates or stops moving away from Twig. It was made so that we can keep using Twig in Toolset with the (many, many) templates we have. 

There, the situation is different, because the Toolset-namespaced version in Twig is used exclusively by Toolset itself, there are no third-party extensions into our Twig templates, etc. etc. We have it under full control and the only concern is keeping an eye on potential security vulnerabilities in Twig and making sure the namespacing process keeps working when we absolutely have to do an upgrade.

**Comment by andreasciamanna** [comment]
It seems I've completely misunderstood the usage if this library :)

I'll look at it again tomorrow.

Sorry :)
